AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EngineVersion :
    Type: String
    Description:  The database Version
    Default: 8.0.28
  AllocatedStorage:
    Type: String
    Description: Allocation storage
    Default: ''
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: must contain only alphanumeric characters.
  DBMaster:
    Type: String
    NoEcho: true
Resources:
  StrapiDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "Subnet Group for Strapi database"
      DBSubnetGroupName: "Blogsubnet"
      SubnetIds:
        - subnet-          #Add Subnet here                                                 
      Tags:
        - Key: Name
          Value: 'DB2'       
  RDSDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: 8.0.28
      MasterUsername: !Ref DBMaster
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - sg-                                  #Add SecurityGroups here
      BackupRetentionPeriod: 7
      DBSubnetGroupName: !Ref StrapiDBSubnetGroup
      MultiAZ: false
      StorageEncrypted: true
      DeletionProtection: true
      PubliclyAccessible: false
  
  RDSDBInstance1:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: 8.0.28
      MasterUsername: !Ref DBMaster
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - sg-                                  #Add SecurityGroups here
      BackupRetentionPeriod: 7
      DBSubnetGroupName: !Ref StrapiDBSubnetGroup
      MultiAZ: false
      StorageEncrypted: true
      DeletionProtection: true
      PubliclyAccessible: false
 

